APP:
  NAME: PatiaTest
BATTERY_TEST:
  DEFAULT_TIME_TO_TEST: 120
  MINIMUM_LEFTOVER: 90
DEFAULT_EMPLOYEE: 1
DEFAULT_VALUES:
  BATTERY: -1
  CAMERA: 0
  CONNECTIVITY: -1
  ETHERNET: 0
  HINGES: 0
  KEYBOARD: 0
  MICROPHONE: 0
  SCREEN: 0
  SPICKERS: 0
  SUPPLY_PLUG: 0
  TOUCHPAD: 0
  TOUCHSCREEN: 5
  USB: 0
SELECTED_PROGRAMS:
- battery_info.exe
- keyboard_test.exe
- MemTest64.exe
WIFI:
  PASS: Pixel12345
  PASS5G: Pixel12345
  SSID: Pixel Lap
  SSID5G: Pixel Lap 5G
